### ISSUE TITLE
Can I derive a similarity score?

### ISSUE THREAD

**Issue by SamihaSara** [sajadamouei/Person-Re-ID-with-light-weight-network#1]
Hello,

Thanks for publishing your work. Is it possible to find the similarity score between search and example images? Also, Could you please add a step by step explanation to run this project(how to train and test)?

**Comment by sajadamouei** [comment]
Hi,
Thank you for reviewing my work. Please provide your Gmail address so I can send you the implementation details, dataset and results. This implementation is done in Google Colab.

**Comment by SamihaSara** [comment]
Hi,
Thanks for replying. My gmail address- samihasara2017@gmail.com
It would be great if you can share weights for pretrained model also. I need to run a demo first.

**Comment by sioncen** [comment]
Hi,
I'm interesting in your work and I want to run the demo, can you also send me your implementation details, dataset and results?My gmail address is         thisissioncen@gmail.com
Thanks!

**Comment by ahih251** [comment]
Hi,
I'm interesting in your work and I want to run the demo, can you send the project detail and saved weights. My gmail address is myiksiks@gmail.com
Thank you so much

**Comment by faviasono** [comment]
Hi,
I'm interesting in your work and I want to run the demo, can you send the project detail and saved weights. My gmail address is [andrea.faviait@gmail.com](mailto:andrea.faviait@gmail.com)
Thank you so much
