### ISSUE TITLE
load dataset

### ISSUE THREAD

**Issue by Sarjanan-Karunanithy** [sajadamouei/Person-Re-ID-with-light-weight-network#2]
npz= np.load('drive/My Drive/thesis/nparray camera/cuhk01.npz')
how get in local machine

**Comment by sajadamouei** [comment]
> npz= np.load('drive/My Drive/thesis/nparray camera/cuhk01.npz')
> how get in local machine

From here:
https://drive.google.com/drive/folders/1DYkJy9xtu1lsgZuys1rZnLwLexlEbFt9?usp=sharing
